import { withPageAuthRequired } from "@auth0/nextjs-auth0"
import AppLayout from "../components/app-layout/AppLayout"
import { getAppProps } from "../utils/db-utils";
import { faCoins } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
// import { useRouter } from "next/router";

export default function TokenTopup() {
  // const router = useRouter();

  const handleClick = async () => {
    const buytokensresult = await fetch(
      '/api/addTokens',
      {
        method: 'POST'
      }
    );

    const json = await buytokensresult.json();

    window.location.href = json.session.url;
  }

  return <div className="w-full h-full flex flex-col overflow-auto">
    <div className="m-auto max-w-screen-sm text-center">
      <FontAwesomeIcon icon={faCoins} className="text-stone-600 text-8xl motion-safe:animate-ping" />
      <h1>Token top-up?</h1>
      <h3 className="text-yellow-500">Need content? Got writer&apos;s block? Need inspiration.  Blood from stone?</h3>
      <p>For $9.00 CAD we&apos;ll give you 10 tokens.</p>
      <p>That&apos;s 10 stories generated by our virtual scribe.</p>
      <button className="btn" onClick={handleClick}>Add tokens</button>
    </div>
  </div>
}

TokenTopup.getLayout = function getLayout(page, pageProps) {
  return <AppLayout {...pageProps}>{page}</AppLayout>
}

export const getServerSideProps = withPageAuthRequired({
  async getServerSideProps(ctx) {
    const appsideprops = await getAppProps(ctx);

    return {
      props: {
        ...appsideprops
      }
    }  
  }
});